### ISSUE TITLE
About clock offset

### ISSUE THREAD

**Issue by arizaini** [Phoenix591/android_device_lge_us996#1]
How to get this offset btw https://github.com/Phoenix591/android_device_lge_us996/blob/7d3ec4c0199b8d05f19952f54f8b18bd64bafa3e/BoardConfig.mk#L81

**Comment by Phoenix591** [comment]
It was just how far off, in seconds, the clock was in twrp when the system was running lineageos (the stock lg rom saves its ats files with no offset needed so unfortunately I handle making the time right for both with a VERY hacky script in recovery/root/fixdate.sh, it used to be less hacky but as I switched the twrp kernel around and roms updated it got complicated). In this case the offset is 46 years in the past (that is, in twrp the date and time were exactly right but 46 years in the future) in seconds
