### ISSUE TITLE
Typo in qseecom service start script 

### ISSUE THREAD

**Issue by imasaru** [Phoenix591/android_device_lge_us996#2]
https://github.com/Phoenix591/android_device_lge_us996/blob/d7414aac520b902c5508620245c2511c879f61a4/recovery/root/init.recovery.elsa.rc#L8

Should this be `group`?

**Comment by Phoenix591** [comment]
Thanks, I didn't catch that typo (the service ran inspite of it), but I fixed it

**Comment by imasaru** [comment]
:man_shrugging:
